### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by DannyFeliz** [Gewaer/mantra#3]
We could start using [Jest](https://jestjs.io/) which is really handly and powerfull.

**Comment by carlospgraciano** [comment]
Hi! @DannyFeliz 

We're surprised but also thankful for the quickness of your support for Mantra.

We've decided that unit testing will be incorporated in Mantra's first release (1.0.0) because we know that Mantra can't be released without unit tests but as of now (0.0.0) we won't be adding unit testing.

Currently, unit tests are not our primary focus because we're in a designing phase where we are still deciding which flows and resources are more convenient to Mantra. This designing phase may bring a lot of changes in how Mantra is being implemented and therefore maintaining unit tests may generate extra work to us since a change in the design will mean a change in the implementation as well as the unit tests.

PD:
Huge thanks for the recommendation of [Jest](https://jestjs.io/). We will be checking it out in order to take it into consideration as Mantra primary testing framework.

I'll be closing this issue (based on the above response).
